function links = LinkPositions(x1,y1,theta,s,phi,L_m1)
%LINKPOSITIONS
%    LINKS = LINKPOSITIONS(X1,Y1,THETA,S,PHI,G,K,L_SP0,L_M1,M1,I1,M2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    08-Jan-2017 21:08:44

t2 = cos(theta);
t3 = sin(theta);
t4 = phi+theta;
links = reshape([x1-L_m1.*t2,y1-L_m1.*t3,x1+L_m1.*t2,y1+L_m1.*t3,x1,y1,x1+s.*sin(t4),y1-s.*cos(t4)],[2,4]);
