function f_cg = F_CoriGrav_fl(x1,y1,theta,s,phi,dx1,dy1,dtheta,ds,dphi,g,k,L_sp0,L_m1,m1,I1,m2)
%F_CORIGRAV
%    F_CG = F_CORIGRAV(X1,Y1,THETA,S,PHI,DX1,DY1,DTHETA,DS,DPHI,G,K,L_SP0,L_M1,M1,I1,M2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    08-Jan-2017 15:39:25

t2 = phi+theta;
t3 = sin(t2);
t4 = cos(t2);
t5 = dphi.^2;
t6 = dtheta.^2;
t7 = dphi.*ds.*2.0;
t8 = ds.*dtheta.*2.0;
t9 = g.*t3;
t10 = t7+t8+t9;
f_cg = [m2.*(dphi+dtheta).*(ds.*t4.*-2.0+dphi.*s.*t3+dtheta.*s.*t3);-g.*m1-g.*m2-dphi.*ds.*m2.*t3.*2.0-ds.*dtheta.*m2.*t3.*2.0-m2.*s.*t4.*t5-m2.*s.*t4.*t6-dphi.*dtheta.*m2.*s.*t4.*2.0;-m2.*s.*t10;L_sp0.*k-k.*s+g.*m2.*t4+m2.*s.*t5+m2.*s.*t6+dphi.*dtheta.*m2.*s.*2.0;-m2.*s.*t10];
