function invM = InvMassMatrix_fl(x1,y1,theta,s,phi,g,k,L_sp0,L_m1,m1,I1,m2)
%INVMASSMATRIX
%    INVM = INVMASSMATRIX(X1,Y1,THETA,S,PHI,G,K,L_SP0,L_M1,M1,I1,M2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    08-Jan-2017 15:39:25

t2 = 1.0./m1;
t3 = phi+theta;
t4 = cos(t3);
t5 = 1.0./s;
t6 = sin(t3);
t7 = 1.0./I1;
t8 = t2.*t4;
t9 = 1.0./m2;
invM = reshape([t2,0.0,0.0,-t2.*t6,-t2.*t4.*t5,0.0,t2,0.0,t8,-t2.*t5.*t6,0.0,0.0,t7,0.0,-t7,-t2.*t6,t8,0.0,t2.*t9.*(m1+m2),0.0,-t2.*t4.*t5,-t2.*t5.*t6,-t7,0.0,1.0./s.^2.*t2.*t7.*t9.*(I1.*m1+I1.*m2+m1.*m2.*s.^2)],[5,5]);
