function CoGs = CoGPositions(x1,y1,theta,s,phi,g,k,L_sp0,L_m1,m1,I1,m2)
%COGPOSITIONS
%    COGS = COGPOSITIONS(X1,Y1,THETA,S,PHI,G,K,L_SP0,L_M1,M1,I1,M2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    09-Jan-2017 01:15:16

t2 = phi+theta;
CoGs = reshape([x1,y1,theta,x1+s.*sin(t2),y1-s.*cos(t2),0.0],[3,2]);
