function links = LinkPositions(x1,y1,theta,s,phi,g,k,L_sp0,L_m1,m1,I1,m2)
%LINKPOSITIONS
%    LINKS = LINKPOSITIONS(X1,Y1,THETA,S,PHI,G,K,L_SP0,L_M1,M1,I1,M2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    09-Jan-2017 01:15:16

t2 = cos(theta);
t3 = sin(theta);
t4 = phi+theta;
links = reshape([x1-L_m1.*t2.*(1.0./2.0),y1-L_m1.*t3.*(1.0./2.0),x1+L_m1.*t2.*(1.0./2.0),y1+L_m1.*t3.*(1.0./2.0),x1,y1,x1+s.*sin(t4),y1-s.*cos(t4)],[2,4]);
