function BodyR = BodyR(s,phi,theta,x2,y2,g,k,L_sp0,L_m1,m1,I1)
%BODYR
%    BODYR = BODYR(S,PHI,THETA,X2,Y2,G,K,L_SP0,L_M1,M1,I1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    08-Jan-2017 23:58:14

t2 = phi-theta;
BodyR = [x2+L_m1.*cos(t2)-s.*sin(phi);L_m1.*sin(t2)+s.*cos(phi)];
