function CoGs = CoGPositions(s,phi,theta,x2,y2,g,k,L_sp0,L_m1,m1,I1)
%COGPOSITIONS
%    COGS = COGPOSITIONS(S,PHI,THETA,X2,Y2,G,K,L_SP0,L_M1,M1,I1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    08-Jan-2017 23:58:14

CoGs = reshape([x2-s.*sin(phi),s.*cos(phi),phi-theta,x2,y2,0.0],[3,2]);
