function JBodyR = ContactJacobianR(s,phi,theta,x2,y2,g,k,L_sp0,L_m1,m1,I1)
%CONTACTJACOBIANR
%    JBODYR = CONTACTJACOBIANR(S,PHI,THETA,X2,Y2,G,K,L_SP0,L_M1,M1,I1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    08-Jan-2017 23:58:14

t2 = phi-theta;
t3 = sin(t2);
t4 = cos(phi);
t5 = sin(phi);
t6 = cos(t2);
t7 = L_m1.*t6;
JBodyR = reshape([-t5,t4,-L_m1.*t3-s.*t4,t7-s.*t5,L_m1.*t3,-t7],[2,3]);
