function links = LinkPositions(s,phi,theta,x2,y2,g,k,L_sp0,L_m1,m1,I1)
%LINKPOSITIONS
%    LINKS = LINKPOSITIONS(S,PHI,THETA,X2,Y2,G,K,L_SP0,L_M1,M1,I1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    08-Jan-2017 23:58:14

t2 = phi-theta;
t3 = cos(t2);
t4 = sin(phi);
t5 = cos(phi);
t6 = s.*t5;
t7 = sin(t2);
links = reshape([x2-L_m1.*t3-s.*t4,t6-L_m1.*t7,x2+L_m1.*t3-s.*t4,t6+L_m1.*t7,x2-s.*t4,t6,x2,y2],[2,4]);
