function M = MassMatrix(s,phi,theta,x2,y2,g,k,L_sp0,L_m1,m1,I1)
%MASSMATRIX
%    M = MASSMATRIX(S,PHI,THETA,X2,Y2,G,K,L_SP0,L_M1,M1,I1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    08-Jan-2017 23:58:13

M = reshape([m1,0.0,0.0,0.0,I1+m1.*s.^2,-I1,0.0,-I1,I1],[3,3]);
